apiVersion: v1
kind: PersistentVolume
metadata:
  name: kepler-nfs-pv
spec:
  capacity:
    storage: 1Gi  
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/nfs_share/kepler
    server: 172.20.10.6
  storageClassName: nfs-client
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kepler-pvc
  namespace: kepler
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
  volumeName: kepler-nfs-pv
