apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - daemonset.yaml
  - service.yaml
  - servicemonitor.yaml
  - prometheus-rbac.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: kepler
      app.kubernetes.io/part-of: kepler

# Must match image: <KEPLER_IMAGE> in daemonset.yaml
images:
  - name: <KEPLER_IMAGE>
    newName: docker.io/mengxue12/kepler
    newTag: v0.11.2-latest
