apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../k8s

patches:
  - target:
      version: v1
      kind: ConfigMap
      name: kepler
      namespace: kepler
    patch: |-
      - op: replace
        path: /data/config.yaml
        value: |
          log:
            level: debug
            format: text
          host:
            sysfs: /host/sys
            procfs: /host/proc
          monitor:
            interval: 1s
            staleness: 500ms
            maxTerminated: 100
            minTerminatedEnergyThreshold: 10
          rapl:
            zones: []
          exporter:
            stdout:
              enabled: false
            prometheus:
              enabled: true
              debugCollectors:
                - go
          web:
            configFile: ""
            listenAddresses:
              - ":28282"
          debug:
            pprof:
              enabled: false
          kube:
            enabled: false
            config: ""
            nodeName: ""
          dev:
            fake-cpu-meter:
              enabled: false
              zones: []
          # EXPERIMENTAL FEATURES - These features are experimental and may be unstable
          # and are disabled by default
          experimental:
            platform:
              redfish:
                enabled: false
                configFile: "/etc/kepler/redfish.yaml"
                nodeName: ""
                httpTimeout: 5s
  - target:
      group: monitoring.coreos.com
      version: v1
      kind: ServiceMonitor
      name: kepler
      namespace: kepler
    patch: |-
      - op: replace
        path: /spec/endpoints/0/interval
        value: 1s
