apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kepler-estimator
  namespace: kepler
  labels:
    app.kubernetes.io/name: kepler
    app.kubernetes.io/part-of: kepler
    app.kubernetes.io/component: estimator-metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: estimator-metrics
  endpoints:
    - port: metrics
      interval: 5s
      path: /metrics
